spring.application.name=demo3
rocketmq.endpoints=rmq-cn-83l41s47x04.cn-shanghai.rmq.aliyuncs.com:8080
rocketmq.topic=topic01
rocketmq.consumer-group=group01
rocketmq.instance-id=rmq-cn-83l41s47x04
rocketmq.username=de2rC7CC7O9zt9LS
rocketmq.password=cEbN1p10nvWdTK72
logging.level.org.example.demo3=DEBUG
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Redis配置
spring.data.redis.host=r-uf6nltbnbpqq6ubcncpd.redis.rds.aliyuncs.com
spring.data.redis.port=6379
spring.data.redis.password=xuXin2010
spring.data.redis.database=0