spring.application.name=demo3
rocketmq.endpoints=rmq-cn-83l41s47x04.cn-shanghai.rmq.aliyuncs.com:8080
rocketmq.topic=topic01
rocketmq.consumer-group=group01
rocketmq.instance-id=rmq-cn-83l41s47x04
rocketmq.username=de2rC7CC7O9zt9LS
rocketmq.password=cEbN1p10nvWdTK72
logging.level.org.example.demo3=DEBUG
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# Redis??
spring.data.redis.host=r-uf6nltbnbpqq6ubcncpd.redis.rds.aliyuncs.com
spring.data.redis.port=6379
spring.data.redis.password=xuXin2010
spring.data.redis.database=0

# MySQL?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/coupon?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=root
spring.datasource.password=your_password

# ????????????
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# MyBatis??
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl